# Generated by Django 4.1.6 on 2023-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_meta_keyword_alter_blog_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_keyword_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keyword_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keyword_uz',
            field=models.TextField(null=True),
        ),
    ]
