# Generated by Django 4.1.6 on 2023-04-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='preview_image',
        ),
    ]
