# Generated by Django 4.1.6 on 2023-04-15 00:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_blog_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='preview_image',
            field=cloudinary.models.CloudinaryField(default='image.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
