# Generated by Django 4.1.6 on 2023-04-21 09:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blog_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
