# Generated by Django 4.1.6 on 2024-04-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body_uz',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_description_uz',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_keyword_uz',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_uz',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
    ]
