# Generated by Django 4.1.6 on 2023-04-13 01:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about_project', models.TextField()),
                ('link', models.URLField()),
                ('preview_photo', cloudinary.models.CloudinaryField(max_length=255)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
