# Generated by Django 4.1.6 on 2023-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
