# Generated by Django 4.1.6 on 2023-04-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_education_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='years',
            field=models.DateField(),
        ),
    ]
