# Generated by Django 4.1.6 on 2023-04-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_education_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
