# Generated by Django 4.1.6 on 2023-04-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_education_experience_alter_experience_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('location', models.URLField(blank=True)),
                ('description', models.TextField(max_length=100)),
                ('years', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Educations',
            },
        ),
    ]
