# Generated by Django 4.1.6 on 2023-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_education_options_education_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='years',
            field=models.DateField(),
        ),
    ]
