# Generated by Django 4.1.6 on 2023-07-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_education_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='web', max_length=30),
            preserve_default=False,
        ),
    ]
