# Generated by Django 4.1.6 on 2023-04-09 09:06

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_category_options_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_course',
            field=models.TextField(default='About course', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='photo',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
