# Generated by Django 4.1.6 on 2023-05-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_coursematerials_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
