# Generated by Django 4.1.6 on 2023-07-08 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0007_remove_course_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='graduates',
            field=models.ManyToManyField(blank=True, related_name='graduates', to=settings.AUTH_USER_MODEL),
        ),
    ]
